name: MQTT Publish on Commit

on:
  push:
    branches:
      - main  # Monitor commits on the 'main' 

jobs:
  publish:
    runs-on: ubuntu-latest # Ubuntu for CI 
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies (Mosquitto + jq)
        run: |
          sudo apt-get update
          sudo apt-get install -y mosquitto-clients jq 

      - name: Extract Latest Firmware URL
        id: extract_url
        run: |
          URL=$(jq -r '.firmware_versions[0].url' versions.json)
          echo "URL=$URL" >> $GITHUB_ENV

      - name: Publish Encrypted URL and MAC to MQTT Topic
        run: |
          mosquitto_pub -h test.mosquitto.org -t "inTopic" -m "$URL"

      - name: Publish Timestamp to MQTT Topic
        run: |
          TIMESTAMP=$(TZ="UTC+3" date +"%Y-%m-%dT%H:%M:%S")
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
          mosquitto_pub -h test.mosquitto.org -t "timestamp" -m "$TIMESTAMP"
          
